docs_dir: doc/book/ru
pages:
    - index.md
site_name: zf-log
site_description: 'Модуль для унификации логирования в проектах на ZF'
repo_url: 'https://github.com/nnx-framework/zf-log'
copyright: 'Copyright (c) 2016 <a href="https://github.com/nnx-framework">NNX</a>'
